name: sam_api_calls
description: A new Dart package.
version: 0.2.0
homepage: http://www.samelement.com

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  dio: ^5.1.2
  path: ^1.8.0
  intl: ^0.19.0
  collection: ^1.15.0
