name: sam_api_calls
description: A new Dart package.
version: 0.1.42
homepage: http://www.samelement.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  path: ^1.8.0
  intl: ^0.17.0
  collection: ^1.15.0